[project]
name = "expance-tracker"
version = "0.1.0"
description = "expance tracker in google sheets and local"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gspread>=6.2.1",
    "matplotlib>=3.10.5",
    "oauth2client>=4.1.3",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
]
