# Generated by Django 5.2.5 on 2025-08-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_paymentmethod_description'),
        ('investment_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.paymentmethod'),
        ),
    ]
